name: Planet Bluesabre
description: All the latest from Xfce, Xubuntu, & Friends
meta_description: "Planet Bluesabre - All the latest from Xfce, Xubuntu, & Friends"
timezone: America/New_York

markdown: kramdown
highlighter: rouge
domain_name: "https://planet.bluesabre.org"

url: "https://planet.bluesabre.org"
author: "Sean Davis"

exclude:
  - build
  - build.sh
  - README.md
