name: Planet Bluesabre
description: All the latest from Xfce, Xubuntu, & Friends
meta_description: "Planet Bluesabre - All the latest from Xfce, Xubuntu, & Friends"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
domain_name: "https://planet.bluesabre.org"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://planet.bluesabre.org"
author: "Sean Davis"

# Disqus config
disqus-shortname: ""
